### ISSUE TITLE
[Request] Zip file support

### ISSUE THREAD

**Issue by Fordi** [nicolas-siplis/IronBoy#10]

**Comment by Chiplis** [comment]
Hey, just so I'm fully clear on what's being requested here.

Some ROM's are downloaded as ZIP instead of .gb files, in that case we could extract the ZIP, keep all .gb files and let people choose any of the available games. If only one game is available, we start it without any more user input.

Would that be the desired behavior on your end?

**Comment by Fordi** [comment]
That would be an ideal implementation, but I think the minimum viable impl would be "immediately plays the first GB/GBC file in the zip header", and would cover 99% of people's use case.
